# @package _global_

type_to_eval: recoil_5TeV

list_to_run_over:
  SUMETUE: 
    transform_func:
      # - - _target_: numpy.abs
      #     _partial_: True
      - _target_: src.utils.undo_log_squash
        _partial_: True

      - _target_: src.utils.undo_log_squash
        _partial_: True

    conds_func:
      - _target_: src.utils.undo_log_squash
        _partial_: True
      - _target_: src.utils.undo_log_squash
        _partial_: True
    xlabels: ${.transport_names}
    transport_names: [u_perp, bias]
    conds_names: [pT_ll, sumEtUE]

integral_conds_name: "pT_ll"
