# @package _global_

type_to_eval: sumETUE_5TeV_W

list_to_run_over:
  SUMETUE: 
    transform_func:
      - _target_: src.utils.undo_log_squash
        _partial_: True
    conds_func:
      - _target_: src.utils.undo_log_squash
        _partial_: True
    xlabels: ${.transport_names}
    transport_names: [sumEtUE]
    conds_names: [uT]

integral_conds_name: "uT"
