# @package _global_

defaults:
  - _self_
  - trainer: default.yaml
  - model: transformer_classifier.yaml
  - data: jetclass_stream.yaml 
  # - data: domain_shift_stream.yaml 
  - wandb: default.yaml
  - hydra: default.yaml
  - paths: default.yaml
  - callbacks: default.yaml
  - experiment: bb_nominal.yaml

seed: 42 # For reproducibility
project_name: latn_calib_clf # Determines output directory path and wandb project
network_name: latn_calib_clf # Used for both saving and wandb
device: cuda # device to use on
