# @package _global_
glob_path: /home/users/a/algren/scratch/trained_networks/hadronic_recoil/new_setup/template_generator/

maxevents: null
save_figures: True
n_bins: 20
truth_names: [label]
signal_label: [1]
signal_name: 'signal'
bkg_name: 'background' # set to None if no background is needed

conds_inte:
  - []

# path: ${glob_path}/2_2/recoil_5TeV_long/
# path: ${glob_path}/1_1/SUMETUE_5TeV/
path: ${glob_path}/1_1/sumEtUE_5TeV_Wp/
# path: ${glob_path}/1_1/sumEtUE_5TeV_Wm/


# path: ${glob_path}/1_1/systematics/sumetue_sherpa/
# path: ${glob_path}/2_2/systematics/recoil_sherpa/
# path: ${glob_path}/1_1/systematics/sumetue_OT_sherpa_to_data/
# path: ${glob_path}/2_2/systematics/recoil_5TeV_OT_sherpa_to_data/

# Data
# data_path:
#     - /home/users/a/algren/scratch/hadronic_recoil/v20230411_fballi_OT_pTZanalysis_bkg_not_working/pTZanalysis_zee_DATA_5TeV/Nominal/*
#     - /home/users/a/algren/scratch/hadronic_recoil/v20230411_fballi_OT_pTZanalysis_bkg_not_working/pTZanalysis_zmumu_DATA_5TeV/Nominal/*

# MC
# data_path:
#     - /home/users/a/algren/scratch/hadronic_recoil/v20230411_fballi_OT_pTZanalysis_bkg_not_working/pTZanalysis_zee_MC_5TeV/Nominal/*
#     - /home/users/a/algren/scratch/hadronic_recoil/v20230411_fballi_OT_pTZanalysis_bkg_not_working/pTZanalysis_zmumu_MC_5TeV/Nominal/*

train:
  dense:
    epochs: 100

  dataloader_kwargs:
    batch_size: 1024
    pin_memory: true
    drop_last: true
    num_workers: 2

model:
  dense:
    input_dim: 3
    using_weights: True
    N: 512
    n_layers: 4
    sigmoid: False
    activation_str: leaky_relu
    output_size: 1
    batchnorm: false
    lr: 1e-4
    device: 'cuda'
