# @package _global_
defaults:
  - _self_

glob_path: /srv/beegfs/scratch/groups/rodem/latn_calib/calibrations/

type_to_eval: JetClass 
name_to_eval: nominal
evaluation_sample: source 
bkg_scaler_str: all
save_figures: True

paths:
  JetClass:  
    # # gaussian transport
    gauss:  ${glob_path}/gaussian/16_gaussian/

    # only 128 classifier
    nominal:  ${glob_path}/JetClass/bb_128_only_model_n_icnn
    
list_to_run_over:
  latn: 
    xlabels: ${.transport_names}
    transport_names: [latn_15]
    # conds_names: ["weights"] # dummy name

# integral_conds_name: "weights"

# conds bins
# weights: [0, 100]
# run_clf_layers: null
# run_clf_layers: [8,2] # 16d for 128
run_clf_layers: 8 # 10d for 128 
# run_clf_layers: 2 # 10d for 16

# which plots to make
discriminators: False
hist_kwargs: True # True or null

discriminator:
  n_epochs: 50
  no_OT_calib: False
  single_layer: false
  use_calib: False
  valid_size: 200_000
  train_size: null

