# @package _global_

hydra:
  run:
    # save config at
    dir: ${get_latn.model_path}/predictions

glob_model_path: /srv/beegfs/scratch/groups/rodem/latn_calib/latn_calib_clf
glob_data_path: /home/users/a/algren/scratch/latn_calib/

chunks_numbers: 90

split_cfg:
  test_size: 0.1

get_latn:
  _target_: src.datamodule.get_latent_of_datasets
  # 512,256,128,64,32,16,10
  model_path: ${glob_model_path}/latn_calib_clf_jetclass_2025_02_03_17_22_09_461014
  layers_removed_lst: [-2, -8, -12]

  # additioal setting
  n_batches: 100 #60_000
  layers_removed: null

  data_paths:
      BigBelloNominal: ${glob_data_path}/nominal_low_and_high_combined.h5
      PSmurr2_smeared: ${glob_data_path}/PSmurr2_smeared_low_and_high_combined.h5
