# @package _global_

_target_: run.predict_ot.PredictionHandler

glob_path: /srv/beegfs/scratch/groups/rodem/latn_calib/calibrations/
glob_samples: /srv/beegfs/scratch/groups/rodem/latn_calib/latn_calib_clf/

# new classifier with flow
model_path:  ${glob_path}/JetClass/bb_latn_128_n_icnn_2
  
sample_name: source
bkg_scaler_str: all # all, only_signal or rm_over_pred 
force_prediction: True
force_new_sample: False
maxevents: 1_000_000
index_to_load: -1 #-300
allow_prediction: True

norm_func:
  _target_: src.datamodule.inverse_norm
  _partial_: true


